stages:
    - test
    - build


image: maven:3.9.2-eclipse-temurin-17-alpine

variables:
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository


cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
        - ".m2/repository"

mvn_test:
    stage: test
    script:
        - echo "testing"
        - mvn test
    artifacts:
        reports:
            junit: target/surefire-reports/*.xml
        when: always
        expire_in: 1 days

mvn_verify:
    stage: build
    script:
        - echo "verify"
        - mvn verify -DskipTests
    artifacts:
        when: on_success
        expire_in: 1 days
        paths:
            - "target/*.jar"