name: Maven test project

on:
  workflow_call

jobs:
  maven_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 0 # include all history and tags
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
#      - name: Get tags
#        run: git fetch --tags origin
      - run: |
          mvn validate
          mvn test
